### ISSUE TITLE
Getting a token each time I log in

### ISSUE THREAD

**Issue by ddeimeke** [onli/feedtragon#18]
Maybe due to your fast updates, I have to request a new login token every day.

If you like to avoid passwords, consider changing to a certificate login.

**Comment by onli** [comment]
I really want to use portier for this project. 

The problem comes from me restarting the server for applying updates. Like now, to make the importing run better.

A solution could be to switch to the gmail address? Then you don't need to go into the email, he will just redirect to login via google. Would that be easier?

**Comment by ddeimeke** [comment]
Yes, this is a workaround, but a bad one. I don't want Google to be my authenticator. It is ok for a test ...

BTW: Portier is being blocked by our company proxy. This means I am not able to access Feedtragon from my work PC.

**Comment by onli** [comment]
Dirk, special thanks for opening this issue. I had no idea there is actually a way to properly solve this. With commit https://github.com/onli/feedtragon/commit/c4fafcdc54de4a166528b5998b9324a6dff2538b sessions will be stored locally and persistently, meaning that when restarting the server they stay valid. I just also enabled that on feedtragon.com (you will have to login once again) and it seems to work fine.

I tried to set a sufficient high expire time, it would be good if we can have a look (just by keeping it in mind) whether that works as intended.

> BTW: Portier is being blocked by our company proxy. This means I am not able to access Feedtragon from my work PC.

I hope the API can be a workaround for that. But why is Portier being blocked, is the proxy giving a reason?

**Comment by ddeimeke** [comment]
Proxy is saying uncategorized URL, I try to categorize it now via https://www.trustedsource.org/en/feedback/url?action=checksingle

(I just wanted to make you aware of other "real" problems that can happen if you rely on third-party-services).

**Comment by onli** [comment]
@ddeimeke is that now working better for you?

**Comment by ddeimeke** [comment]
Yes, it does.
