### ISSUE TITLE
Specify the rights for the tokens

### ISSUE THREAD

**Issue by julien51** [onli/feedtragon#5]
When creating a Superfeedr token, it would be great if the user knew the rights required by Feedtragon.

**Comment by onli** [comment]
Is there a way to have there an url like `https://superfeedr.com/users//tokens/new&rights=subscribe,unsubscribe` that leads to the new taken form with the needed rights preselected?

**Comment by julien51** [comment]
That's a neat idea and we just deployed the code which does it :)

https://superfeedr.com/tokens/new?label=feedtragon&acl_subscribe=true&acl_unsubscribe=true&acl_list=true&acl_retrieve=true

**Comment by onli** [comment]
Great, thanks!
