### ISSUE TITLE
Configure the domain?

### ISSUE THREAD

**Issue by julien51** [onli/feedtragon#6]
For some reason, all callbacks created on Superfeedr are using `http://localhost/...` which is annoying because of course, Superfeedr won't be able to send notifcations to my local machine, even though I use `runscope`'s [passageway](https://www.runscope.com/docs/passageway).

Any idea how to configure this?

**Comment by onli** [comment]
feedtragon is setting the callback url via sinatra's url helper, in https://github.com/onli/feedtragon/blob/d538a336771eece529a1818d48524615295318c6/server.rb#L98. When that is localhost, it means that the url helper think you are running under localhost - ah, and running under passageway, that is probably exactly what is happening.

You might just want to replace that line with one setting base_path to the url you want. In the long run, I probably should add an option to overwrite that.

EDIT: Oh, that is wrong. Feedtragon is only setting a relative url, which means it'd need to set a domain in rack-superfeedr.

**Comment by onli** [comment]
I now looked into that more carefully. Sorry for the confusion.

Feedtragon is indeed already setting Rack::Superfeedr.host, https://github.com/onli/feedtragon/blob/d538a336771eece529a1818d48524615295318c6/server.rb#L47. He is saving the host where the installer is running from into the database, https://github.com/onli/feedtragon/blob/d538a336771eece529a1818d48524615295318c6/server.rb#L211. If I wanted to try out whether `URI(url('/')).host` is working better in you scenario, I'd just have to host it on localhost and enter via passageway?

For the time being, easiest for you would be to change the option in the **database.db** with the sqlite3 client:

```
UPDATE options SET value = "new.host" WHERE name = "host";
```

I'll try to add an option to make that configurable in the settings page later.

**Comment by onli** [comment]
@julien51, did the sqlite command work? If not or if you didn't try yet, I just added a configuration block for the superfeedr setting: https://github.com/onli/feedtragon/commit/29173196f75852dde37dfbc561b779adc50199c1

Now that should be easier.

**Comment by julien51** [comment]
Onli, I haven't had the time to look at this... Now, the easier it is to
set this, the better!
I think I won't be the only one using such a setting. Think about people
deploying on platforms like Heroku for example.

**Comment by onli** [comment]
Agreed :) I will close here for now, if anything doesn't work with it, please just comment and I'll reopen.
